### ISSUE TITLE
Viewed

### ISSUE THREAD

**Issue by tzmbzt** [Xon/XenForo-UserActivity#3]
The old version could show who viewed a thread (and such). Why was this removed or can it be added again ?

**Comment by Xon** [comment]
This does show who is viewing a thread, what it doesn't show is who has read a thread. The thread read tracking data is regularly purged and I did not need it when I was building my own version.

**Comment by tzmbzt** [comment]
I think this a feature that reallllly wanted. Sometimes is more interesting to know if people already saw a thread, rather then if they are currently viewing it.

I upgraded to this version and did not know. You might consider it as an option at least. Thanks.

**Comment by Xon** [comment]
I am open to pull requests, but am unlikely to be adding that feature any time soon
